qtmultimedia: Autospec creation for update from version 5.13.1 to 5.13.2
Andrew Smolko (1):
      AVFoundation: Re-create CARenderer if current OpenGL context changed

Antti Kokko (2):
      Add changes file for Qt 5.12.5
      Add changes file for Qt 5.13.2

Christian Stenger (1):
      Fix building with namespaced Qt

Frederik Gladhorn (1):
      Bump version

Joerg Bornemann (1):
      Fix build with ALSA in non-system location

Marc Mutz (1):
      AVFCameraUtility: fix UB (std::sort with unfit predicate)

Mariana Meireles (1):
      Extract QAudioProbe code snippet

Paul Wicking (1):
      Merge 5.12 into 5.12.5

Qt Forward Merge Bot (12):
      Merge remote-tracking branch 'origin/5.12' into 5.13
      Merge "Merge remote-tracking branch 'origin/5.12' into 5.13"
      Merge remote-tracking branch 'origin/5.12' into 5.13
      Merge "Merge remote-tracking branch 'origin/5.12' into 5.13"
      Merge remote-tracking branch 'origin/5.12' into 5.13
      Merge "Merge remote-tracking branch 'origin/5.12' into 5.13"
      Merge remote-tracking branch 'origin/5.13.1' into 5.13
      Merge "Merge remote-tracking branch 'origin/5.13.1' into 5.13"
      Merge remote-tracking branch 'origin/5.12.5' into 5.12
      Merge "Merge remote-tracking branch 'origin/5.12.5' into 5.12"
      Merge remote-tracking branch 'origin/5.12' into 5.13
      Merge "Merge remote-tracking branch 'origin/5.12' into 5.13"

Ratchanan Srirattanamet (3):
      CameraBin: do fetch viewfinder settings even after LoadedStatus
      Gstreamer: also remove features when simplifying caps
      Create QML camera.viewfinder eagerly

Rolf Eike Beer (4):
      QMediaPlayer: use new connect syntax
      MultimediaGstTools: fix string warnings when defining DEBUG_PLAYBIN
      QGstreamerPlayerSession: build list of debug strings only once
      GstreamerPlayerControl: use new style connect syntax

VaL Doroshchuk (14):
      GStreamer: Allow audio/x-raw codec in QAudioRecorder
      GStreamer: Don't share video surfaces between several pipelines
      Fix undefined reference to QVideoSurfacePainter::~QVideoSurfacePainter
      GStreamer: Don't seek to the beginning when playing is requested
      CameraBinV4LImageProcessing: Show warning only if the camera is loaded
      GStreamer: Add docs for custom pipelines
      CameraBinV4LImageProcessing: Show additional info in case of errors
      Fix crash when VideoOutput.sourceRect is requested but playback is stopped
      GStreamer: Use member initialization
      Fix deprecation condition for QMediaResource
      Move QVideoFrame::Format_ABGR32 to the end of the Pixel Formats
      GStreamer: Recreate playbin after custom pipeline
      imx6: Fix mapping VPU texture using real physical address of data
      AVF: Emit StalledMedia when unbuffered and resume playback afterwards

Val Doroshchuk (14):
      DirectShow: Fix crash when there is no surface on flush()
      DirectShow: Add startTime and endTime to QVideoFrame
      Include moc files after QT_END_NAMESPACE
      DirectShow: Allow QMediaPlayer in secondary thread
      DirectShow: Implement QMediaVideoProbeControl->flush
      DirectShow: Fix tst_QMediaPlayerBackend::surfaceTest
      Fix leaking QVideoFilterRunnable when window is closed
      DirectShow: Fix tst_QMediaPlayerBackend::seekPauseSeek
      DirectShow: Emit media status before error
      DirectShow: Don't seek if playback is stopped
      Override QGraphicsItem::type in QGraphicsVideoItem
      DirectShow: Fix crash when media in qrc is set twice
      WinRT: Ignore media in MediaPlayer only if stream is not changed too
      Fix qConvertFuncs to respect QVideoFrame::Format_ABGR32 in the end